# Generated by Django 3.2.6 on 2021-09-06 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['choice_text']},
        ),
    ]
