# Generated by Django 3.1 on 2020-11-06 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_delete_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
