# Generated by Django 3.2.6 on 2021-11-01 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_choice_options'),
        ('polls', '0009_remove_vote_question'),
    ]

    operations = [
    ]
